module.exports = {
  china: "中国",
  beijing: "北京市",
  huairou: "怀柔区",
  yanqing: "延庆区",
  miyun: "密云区",
  changping: "昌平区",
  shunyi: "顺义区",
  pinggu: "平谷区",
  mentougou: "门头沟区",
  haidian: "海淀区",
  chaoyangqu: "朝阳区",
  fangshanqu: "房山区",
  daxingqu: "大兴区",
  shijingshan: "石景山区",
  fengtai: "丰台区",
  xichengqu: "西城区",
  dongchengqu: "东城区",
  tongzhouqu: "通州区"
};
